export DYLD_INSERT_LIBRARIES=/Users/jlettner/work/objc4-532.2/build/Debug/libobjc.A.dylib
export OBJC_DISABLE_VTABLES=1
export OBJC_PRINT_VTABLE_SETUP=1
export OBJC_PRINT_CLASS_SETUP=1
export OBJC_PRINT_IVAR_SETUP=1
export OBJC_DEBUG_NONFRAGILE_IVARS=1
export OBJC_PRINT_REPLACED_METHODS=1
export OBJC_PRINT_DEPRECATION_WARNINGS=1
export OBJC_DEBUG_NIL_SYNC=1
~/work/HelloWorld/build/Release/HelloWorld
